# -*- coding: utf-8 -*-
"""IRIS-PRM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvEIeUeZnZjJOjU33IVWLnP43DrFXxVY
"""

import random
import math
import heapq
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageOps, ImageDraw
from io import BytesIO
import requests

# define note class in the road map
class Node:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.edges = []

    def add_edge(self, node):
        self.edges.append(node)

    def __lt__(self, other):
        return (self.x, self.y) < (other.x, other.y)

    def __hash__(self):
        return hash((self.x, self.y))

    def __eq__(self, other):
        return (self.x, self.y) == (other.x, other.y)

# define the distance between two notes
def distance(node1, node2):
    return math.sqrt((node1.x - node2.x)**2 + (node1.y - node2.y)**2)

# is node in the obstacles
def node_in_obstacle(node, obstacle_map):
    return obstacle_map[int(node.y), int(node.x)] == 0

# is the link between note1 and note2 passing obstacles
def link_in_obstacle(node1, node2, obstacle_map):
    line_x= np.linspace(node1.x, node2.x, 10)
    line_y= np.linspace(node1.y, node2.y, 10)
    for x, y in zip(line_x, line_y):
        if obstacle_map[int(y), int(x)] ==0:
            return True
    return False

# genearte random node on a obstacle map
def generate_random_nodes(num_nodes, obstacle_map):
    x_max, y_max = obstacle_map.shape[1], obstacle_map.shape[0]
    nodes = []
    while len(nodes) < num_nodes:
        x = random.uniform(0, x_max)
        y = random.uniform(0, y_max)
        node = Node(x, y)
        nodes.append(Node(x, y))
    return nodes

# remove random node on obstacles
def filter_nodes(nodes, obstacle_map):
    filtered_nodes = []
    for node in nodes:
        if not node_in_obstacle(node, obstacle_map):
            filtered_nodes.append(node)
    return filtered_nodes


# link two neighbour nodes on a obstacle map using  k-nearest search
def link_nodes(nodes, k, obstacle_map):
    for node in nodes:
        distances = []
        for other_node in nodes:
            if node != other_node and not link_in_obstacle(node, other_node, obstacle_map):
                distances.append((distance(node, other_node), other_node))
        distances.sort(key=lambda x: x[0])

        for d, other_node in distances[:k]:
            node.add_edge(other_node)
            other_node.add_edge(node)

# implementation of a star search algorithm
def a_star(start_node, goal_node, nodes):
    open_list = []
    heapq.heappush(open_list, (0, start_node))
    came_from = {}

    # cost-so-far
    g_score = {node: float('inf') for node in nodes}
    g_score[start_node] = 0

    # total cost: cost-so-far + estimated cost-to-go
    f_score = {node: float('inf') for node in nodes}
    f_score[start_node] = distance(start_node, goal_node)

    while open_list:

        # pop up the first note to expand the tree
        _, current_node = heapq.heappop(open_list)

        if current_node == goal_node:
            path = []
            while current_node in came_from:
                path.append(current_node)
                current_node = came_from[current_node]
            path.append(start_node)
            return path[::-1]

        for neighbor_node in current_node.edges:
            tentative_g_score = g_score[current_node] + distance(current_node, neighbor_node)
            if tentative_g_score < g_score[neighbor_node]:
                came_from[neighbor_node] = current_node
                g_score[neighbor_node] = tentative_g_score
                f_score[neighbor_node] = tentative_g_score + distance(neighbor_node, goal_node)
                heapq.heappush(open_list, (f_score[neighbor_node], neighbor_node))

    return None


def plot_prm(start_node=None, goal_node=None, nodes=None, path=None, obstacle_map=None):
    if obstacle_map is not None:
        plt.imshow(obstacle_map, cmap='gray', origin='lower')

    if nodes:
      for node in nodes:
          for edge in node.edges:
              plt.plot([node.x, edge.x], [node.y, edge.y], 'k-', lw=0.5)
      plt.scatter([node.x for node in nodes], [node.y for node in nodes], c='b')

    if path:
        path_x = [node.x for node in path]
        path_y = [node.y for node in path]
        plt.plot(path_x, path_y, 'r-', lw=2)

    if start_node and goal_node:
        plt.scatter([start_node.x], [start_node.y], c='g', marker='o')
        plt.scatter([goal_node.x], [goal_node.y], c='r', marker='x')

    plt.show()

np.random.seed(1)


url = "https://github.com/asu-iris/course_robotics/raw/main/lec6-mp/figures/Obstacle.png"
response = requests.get(url)
original_image = Image.open(BytesIO(response.content)).convert('L')
obstacle_map = np.array(original_image)


plot_prm(obstacle_map=obstacle_map)

# generate random node
num_nodes = 200
nodes = generate_random_nodes(num_nodes, obstacle_map)

plot_prm(obstacle_map=obstacle_map, nodes=nodes)

# filter the random node to remove those on obstacles
nodes = filter_nodes(nodes, obstacle_map=obstacle_map)
plot_prm(obstacle_map=obstacle_map, nodes=nodes)

# connect nodes to establish roadmap using k-nearest search
k = 10
link_nodes(nodes, k, obstacle_map)
plot_prm(obstacle_map=obstacle_map, nodes=nodes)

# do a star search on the roadmap
start_node = nodes[1]
goal_node = nodes[-3]
path = a_star(start_node, goal_node,nodes)


# print and plot
if path:
    print("Path found:")
    for node in path:
        print(f"Node: ({node.x}, {node.y})")
else:
    print("No path found")

plot_prm(start_node, goal_node, nodes, path, obstacle_map)
def extract_obstacle_rectangles(obstacle_map):
    """
    Detects each separate black obstacle rectangle.
    Returns a list of (x_min, x_max, y_min, y_max).
    """

    import cv2
    import numpy as np

    # Ensure binary: obstacles = 0, free = 255
    _, thresh = cv2.threshold(obstacle_map, 127, 255, cv2.THRESH_BINARY_INV)

    # Find connected components
    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(thresh)

    rectangles = []

    # stats: [label][x, y, width, height, area]
    # skip label 0 → background
    for i in range(1, num_labels):
        x = int(stats[i][0])
        y = int(stats[i][1])
        w = int(stats[i][2])
        h = int(stats[i][3])

        x_min = x
        x_max = x + w
        y_min = y
        y_max = y + h

        rectangles.append((x_min, x_max, y_min, y_max))

    return rectangles
def build_prm_and_plan(start_xy, goal_xy, num_nodes=200, k=10):
    # 1) Load obstacle image  -> obstacle_map (uint8 array)
    url = "https://github.com/asu-iris/course_robotics/raw/main/lec6-mp/figures/Obstacle.png"
    response = requests.get(url)
    original_image = Image.open(BytesIO(response.content)).convert('L')
    obstacle_map = np.array(original_image)

    # 2) Build PRM (use your existing helpers)
    nodes = generate_random_nodes(num_nodes, obstacle_map)
    nodes = filter_nodes(nodes, obstacle_map)
    link_nodes(nodes, k, obstacle_map)

    # 3) Add start & goal nodes
    start_node = Node(*start_xy)
    goal_node  = Node(*goal_xy)
    nodes.extend([start_node, goal_node])
    link_nodes(nodes, k, obstacle_map)

    # 4) Plan with A*
    path = a_star(start_node, goal_node, nodes)

    return path, obstacle_map


def pixel_to_world(node, obstacle_map, world_w=4.0, world_h=4.0):
    """Map image pixels to MuJoCo world (meters) on a 4m x 4m floor."""
    h, w = obstacle_map.shape
    x_m = (node.x / w - 0.5) * world_w
    y_m = (node.y / h - 0.5) * world_h
    return x_m, y_m

